### PR TITLE
FIX: error when hitting <c-q> to send content to quickfix windows in Telescope picker

### PR DESCRIPTION
**Pull request by benfowler**
This PR is for @pdckxd 's quick-fix window fix. I merged this change earlier, and things regressed, so I'm reopening as draft to investigate.

Tracked as issue #29 .

### CODE REVIEW

**Comment by benfowler** [comment]
@pdckxd : I've re-tested, and modified your change to reinstate a line you removed in your PR -- the `ordinal` attribute of the entry object in the row generation function. It appears to be mandatory.

I've done some testing locally. I've also wiped my Lazy plugin cache and tested again under a clean install to verify it works with a clean Neovim install.

**Comment by benfowler** [comment]
@pdckxd , I haven't heard back, and I've been using this branch for a week without issue. I'm going to just go ahead and merge it.

**Comment by pdckxd** [comment]
@benfowler ,didn't get chance to see inbox for several weeks. Thanks to take the MR.

**Comment by benfowler** [comment]
@pdckxd you're welcome! I hope that problem is solved for you.

**Pull request merged**
